### ISSUE TITLE
Choose ipfs gateway

### ISSUE THREAD

**Issue by MCTaylor17** [fission-suite/ghost-storage-adapter-ipfs#1]
# Summary
As per the original all idea on talk forum:

> Choose which gateway to use. Defaults to ipfs.io, or add your own – e.g. ipfs.runfission.com

# Solution
Fission client has the ability to specify a `baseUrl`.  Consider using either environment variables or the adapter options to set this.

A default can either be declared in the adapter or use the default built into Fission client.

**Comment by bmann** [comment]
Yes this should be an env variable. Can be set in app.json for Heroku deployment.

**Comment by bmann** [comment]
Ah, I guess this was auto-closed because of the Working Beta.

So, left to do is to make this an env var in app.json, and then have the storage adapter read this from the environment.

**Comment by MCTaylor17** [comment]
@bmann, I should have added a note explaining why this was closed.  Currently I've written the storage adapter to be naive about the environment.  All of the variables (user, pass, and url) are passed in as an options parameter by the Ghost config like so:

```json
"storage": {
    "active": "ghost-storage-adapter-ipfs",
    "ghost-storage-adapter-ipfs": {
        "username": "abc",
        "password": "xyz",
        "baseURL": "https://runfission.com"
    }
}
```
Right now, the baseURL is user configurable by adjusting `INTERPLANETARY_FISSION_URL` which is injected into the config over here:

https://github.com/fission-suite/heroku-ipfs-ghost/blob/85110849be7c4ce60942e9306fabc85b970bfe48/bin/create-config#L22

If nothing is provided, it will use the default baseURL from Fission client based on this:

https://github.com/fission-suite/ghost-storage-adapter-ipfs/blob/55f559b8103abee0bba069c6278280e504682dd7/utils.js#L36

Does this sound good?

It's my (invisible) intention to document this in the README.

**Comment by bmann** [comment]
The base URL is our API host — which also happens to be our IPFS gateway. If that gets edited then everything breaks ;)

It’s future proof so someone can run their own version of the Web API server. 

There should be a separate env var that is like IPFS_GATEWAY and could be ipfs.io or a custom domain mapped to Cloudflare’s gateway etc etc

**Comment by MCTaylor17** [comment]
I understand now...

I'll leave the baseURL stuff as is (maybe rename to apiURL) then accept a new parameter (maybe gatewayURL) and swap out this line:

https://github.com/fission-suite/ghost-storage-adapter-ipfs/blob/55f559b8103abee0bba069c6278280e504682dd7/index.js#L19

For something a little better than this:
```js
resolve(this.gatewayURL + cid)
```
👍

**Comment by MCTaylor17** [comment]
And default to `ipfs.io` 😉
