### ISSUE TITLE
IPFS Client Side Enhancement

### ISSUE THREAD

**Issue by MCTaylor17** [fission-suite/ghost-storage-adapter-ipfs#7]
In order to gain access to the enhanced IPFS features, Ghost's [code injection](https://ghost.org/blog/code-injection/) feature could be used to manage the client side implementation.

**Challenge:**
Unless I'm mistaken or things have changed, there's no way to prevent images from being requested without changing the HTML itself.  In other words, if a page is sent with `<img src="https://ipfs.io/ipfs/QmAbC...XyZ"/>` the request will be sent to the gateway before any JS has an opportunity to stop it.

Unfortunately, without modifying the Ghost core (😨), we have to work with the HTML we're provided... 

**Potential solution:**
Assuming we know code injection is available (either requiring it or adding an opt-in flag like `enhancedIPFS: true`) we set the initial `src` attribute to a bad url.  For example:
* `<img src="#QmAbC...XyZ"/>`
* `<img src="https://ipfs.runfission.com/noop/QmAbC...XyZ"/>`

The first example would likely show a broken image while the second could be configured to return a temporary 1x1 pixel.  At that point, the `src` could be parsed for the CID and handled accordingly.

Additional parameters could be placed into query paramaeters.  For example:
* `<img src="#QmAbC...XyZ?gatewayURL=https%3A%2F%2Fipfs.io%2Fipfs"/>` - Gateway to use if IPFS isn't available
* `<img src="#QmAbC...XyZ?height=1080&width=1920"/>` - Construct an accurate placeholder while pending download

**Comment by bmann** [comment]
Short answer: IPFS Companion and various other browser plugins intercept DNS requests and replace calls to known gateways and/or domains with dnslink entries to be served from a local IPFS daemon. 

Long answer: doing more interesting things with systems designed for http will take more work and may only make a certain amount of sense. And many / most may not work within the plugin or adapter system. 

eg

Integrating the get-IPFS script to include a JS IPFS node that gets downloaded to user browsers and fetches IPFS content that way. 

using Ghost as a backend editor to publish a static front end to IPFS.

Publishing individual pages or posts to IPFS. 

Turning a ghost blog into a PWA that caches content.
